// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class LudoEraResources
{
        public const string achievement_first_loss = "CgkItPyqxKsPEAIQAA"; // <GPGSID>
        public const string achievement_statue = "CgkItPyqxKsPEAIQEA"; // <GPGSID>
        public const string achievement_5_losses = "CgkItPyqxKsPEAIQEw"; // <GPGSID>
        public const string achievement_home_safe = "CgkItPyqxKsPEAIQCw"; // <GPGSID>
        public const string achievement_last_man_standing = "CgkItPyqxKsPEAIQAQ"; // <GPGSID>
        public const string achievement_bait = "CgkItPyqxKsPEAIQAg"; // <GPGSID>
        public const string achievement_pawn_pyramid = "CgkItPyqxKsPEAIQCg"; // <GPGSID>
        public const string achievement_lucky_hand = "CgkItPyqxKsPEAIQCQ"; // <GPGSID>
        public const string achievement_kill_streak_1 = "CgkItPyqxKsPEAIQAw"; // <GPGSID>
        public const string achievement_kill_streak_2 = "CgkItPyqxKsPEAIQBA"; // <GPGSID>
        public const string achievement_kill_streak_3 = "CgkItPyqxKsPEAIQBQ"; // <GPGSID>
        public const string achievement_godlike = "CgkItPyqxKsPEAIQEQ"; // <GPGSID>
        public const string achievement_5_wins = "CgkItPyqxKsPEAIQEg"; // <GPGSID>
        public const string achievement_death_streak_1 = "CgkItPyqxKsPEAIQBg"; // <GPGSID>
        public const string achievement_death_streak_2 = "CgkItPyqxKsPEAIQBw"; // <GPGSID>
        public const string achievement_death_streak_3 = "CgkItPyqxKsPEAIQCA"; // <GPGSID>
        public const string achievement_everyone_but_me = "CgkItPyqxKsPEAIQDA"; // <GPGSID>
        public const string achievement_unlucky = "CgkItPyqxKsPEAIQDQ"; // <GPGSID>
        public const string achievement_taste_of_victory = "CgkItPyqxKsPEAIQDw"; // <GPGSID>
        public const string achievement_first_mp_win = "CgkItPyqxKsPEAIQFQ"; // <GPGSID>
        public const string achievement_first_sp_win = "CgkItPyqxKsPEAIQFA"; // <GPGSID>
        public const string achievement_ducking_for_cover = "CgkItPyqxKsPEAIQDg"; // <GPGSID>

}

